# count : 각 세대별 자식이 없는 개체의 수, generation : 세대
WITH RECURSIVE PARENT AS (
    # 최상위 세대
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    # 부모 -> 자식 -> ...
    SELECT C.ID, C.PARENT_ID, P.GENERATION + 1
    FROM ECOLI_DATA C
    JOIN PARENT P ON C.PARENT_ID = P.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM PARENT P
WHERE P.ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION ASC;