SELECT YEAR, (M - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA AS C
    JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
                 MAX(SIZE_OF_COLONY) AS M
          FROM ECOLI_DATA
          GROUP BY YEAR(DIFFERENTIATION_DATE)) AS D
    ON YEAR(C.DIFFERENTIATION_DATE) = D.YEAR
ORDER BY YEAR, YEAR_DEV ASC;